import assert from "node:assert/strict";
import test from "node:test";
import { DEFAULT_TESTING_PRACTICES, InMemoryTestingEventStore, TestingPracticeMemory, type TestingEvent, type VerificationDefinition } from "../src/testing/index.js";

const runId = "testing-run"; let n = 0;
type EventInput = TestingEvent extends infer E ? E extends TestingEvent ? Omit<E, "eventId" | "runId" | "observedAt"> : never : never;
const ev = (value: EventInput): TestingEvent => ({ ...value, eventId: `e${++n}`, runId, observedAt: new Date().toISOString() } as TestingEvent);
const def = (overrides: Partial<VerificationDefinition> = {}): VerificationDefinition => ({ verificationId: "v1", runId, source: { type: "starting_request", ref: "prompt:test", authoritative: true }, ownerId: "verifier", artifacts: ["app.py"], practiceRefs: [], command: "python3 app.py", requiredAssertions: ["scenario passes"], boundary: false, maxRetries: 2, ...overrides });
async function memory() { return TestingPracticeMemory.open(runId, new InMemoryTestingEventStore(), DEFAULT_TESTING_PRACTICES); }

test("retrieval is sparse, hard-filtered, and does not declare verification", async () => { const m = await memory(); assert.deepEqual(m.search({ artifactType: "unknown", risk: "nothing" }), []); const found = m.search({ artifactType: "api", action: "integrate", risk: "contract_mismatch", surface: "boundary" }); assert.deepEqual(found.map((x) => x.practiceId), ["boundary-negative-atomicity"]); assert.deepEqual(m.list(), []); });
test("workers extract only standards assigned to their responsibility", async () => { const m = await memory(); await m.record(ev({ type: "verification.declared", definition: def({ ownerId: "agent2", practiceRefs: ["current-artifact-rerun"] }) })); assert.equal(m.projectForOwner("agent1").length, 0); const view = m.projectForOwner("agent2"); assert.equal(view.length, 1); assert.deepEqual(view[0]?.practices.map((p) => p?.practiceId), ["current-artifact-rerun"]); });
test("authoritative declaration blocks until objective current evidence passes", async () => { const m = await memory(); await m.record(ev({ type: "verification.declared", definition: def() })); assert.equal(m.completionDecision().decision, "block"); await m.record(ev({ type: "artifact.observed", verificationId: "v1", artifactId: "app.py", version: "sha1" })); await m.record(ev({ type: "verification.started", verificationId: "v1", command: "python3 app.py" })); await m.record(ev({ type: "verification.observed", verificationId: "v1", evidence: { evidenceId: "tool-1", command: "python3 app.py", cwd: "/work", exitCode: 0, startedAt: "a", endedAt: "b", artifactVersions: { "app.py": "sha1" }, assertionsObserved: ["scenario passes"], stdoutRef: "blob:out", stderrRef: "blob:err", realPath: true } })); assert.equal(m.get("v1")?.state, "passed"); assert.equal(m.completionDecision().decision, "allow"); });
test("artifact edit makes passed evidence stale", async () => { const m = await memory(); await m.record(ev({ type: "verification.declared", definition: def() })); await m.record(ev({ type: "artifact.observed", verificationId: "v1", artifactId: "app.py", version: "sha1" })); await m.record(ev({ type: "verification.observed", verificationId: "v1", evidence: { evidenceId: "x", command: "python3 app.py", cwd: "/w", exitCode: 0, startedAt: "a", endedAt: "b", artifactVersions: { "app.py": "sha1" }, assertionsObserved: ["scenario passes"], stdoutRef: "o", stderrRef: "e", realPath: true } })); await m.record(ev({ type: "artifact.observed", verificationId: "v1", artifactId: "app.py", version: "sha2" })); assert.equal(m.get("v1")?.state, "stale"); assert.equal(m.completionDecision().decision, "block"); });
test("success prose cannot set passed and disconnected evidence cannot verify boundary", async () => { const m = await memory(); await m.record(ev({ type: "verification.declared", definition: def({ boundary: true }) })); await m.record(ev({ type: "artifact.observed", verificationId: "v1", artifactId: "app.py", version: "sha" })); assert.equal(m.get("v1")?.state, "pending"); await assert.rejects(() => m.record(ev({ type: "verification.observed", verificationId: "v1", evidence: { evidenceId: "claim", command: "python3 app.py", cwd: "/w", exitCode: 0, startedAt: "a", endedAt: "b", artifactVersions: { "app.py": "sha" }, assertionsObserved: ["scenario passes"], stdoutRef: "agent says passed", stderrRef: "none", realPath: false } })), /disconnected mock/); });
test("failure is preserved and bounded repair must rerun original command", async () => { const m = await memory(); await m.record(ev({ type: "verification.declared", definition: def() })); await m.record(ev({ type: "artifact.observed", verificationId: "v1", artifactId: "app.py", version: "sha" })); await m.record(ev({ type: "verification.observed", verificationId: "v1", evidence: { evidenceId: "fail", command: "python3 app.py", cwd: "/w", exitCode: 1, startedAt: "a", endedAt: "b", artifactVersions: { "app.py": "sha" }, assertionsObserved: ["scenario passes"], stdoutRef: "o", stderrRef: "e", realPath: true } })); await m.record(ev({ type: "repair.assigned", verificationId: "v1", repair: { ownerId: "fixer", strategy: "fix state transition", attempt: 1, evidenceRef: "fail" } })); assert.equal(m.get("v1")?.evidence[0]?.exitCode, 1); assert.equal(m.get("v1")?.state, "repair_pending"); await assert.rejects(() => m.record(ev({ type: "verification.started", verificationId: "v1", command: "echo easy" })), /original acceptance command/); });
