import type { TestingPractice } from "./types.js";

export const DEFAULT_TESTING_PRACTICES: TestingPractice[] = [
  { practiceId: "malformed-roundtrip", title: "Malformed input and round trip", state: "active", applicability: { artifactTypes: ["parser", "serializer"], actions: ["implement", "repair"], risks: ["invalid_input", "data_loss"], surfaces: ["unit", "integration"] }, rule: "Check a valid round trip and malformed inputs without partial output.", requiredEvidence: ["exact command", "exit status", "assertion summary", "artifact versions"], invalidSubstitutes: ["file existence", "happy path only", "agent success statement"], failureAction: "repair parsing semantics and rerun the same cases", confidence: .9, cost: 1, successfulRuns: [], counterexamples: [] },
  { practiceId: "boundary-negative-atomicity", title: "Real boundary and negative atomicity", state: "active", applicability: { artifactTypes: ["api", "shared_state", "interface"], actions: ["integrate", "repair"], risks: ["invalid_input", "partial_mutation", "contract_mismatch"], surfaces: ["boundary", "integration"] }, rule: "Exercise the real producer-to-consumer path for valid and invalid input; assert rejection leaves state unchanged.", requiredEvidence: ["real path", "exact command", "exit status", "pre/post assertions", "artifact versions"], invalidSubstitutes: ["producer-only unit test", "consumer mock", "agent success statement"], failureAction: "repair the crossing and rerun the identical boundary check", confidence: .95, cost: 2, successfulRuns: [], counterexamples: [] },
  { practiceId: "clean-environment-startup", title: "Clean-environment import and startup", state: "active", applicability: { artifactTypes: ["package", "application"], actions: ["verify", "repair"], risks: ["import_failure", "environment_contamination"], surfaces: ["startup", "integration"] }, rule: "Run import/startup from the current workspace with explicit isolation and assert loaded module paths.", requiredEvidence: ["exact command", "module path", "exit status"], invalidSubstitutes: ["test using another checkout", "editable install from stale workspace"], failureAction: "isolate the workspace and rerun the same startup check", confidence: .92, cost: 1, successfulRuns: [], counterexamples: [] },
  { practiceId: "deterministic-concurrency", title: "Deterministic concurrency invariant", state: "active", applicability: { artifactTypes: ["shared_state", "service"], actions: ["implement", "verify", "repair"], risks: ["race", "lost_update"], surfaces: ["integration", "system"] }, rule: "Control interleavings and assert state invariants rather than relying on timing.", requiredEvidence: ["repeatable schedule", "state assertions", "exit status"], invalidSubstitutes: ["sleep-based smoke test", "single execution"], failureAction: "repair synchronization and rerun the controlled schedule", confidence: .88, cost: 2, successfulRuns: [], counterexamples: [] },
  { practiceId: "current-artifact-rerun", title: "Current artifact rerun", state: "active", applicability: { artifactTypes: ["code", "package", "application", "api", "interface", "shared_state"], actions: ["verify", "finalize", "repair"], risks: ["stale_evidence", "regression"], surfaces: ["unit", "boundary", "integration", "system", "startup"] }, rule: "Rerun the original acceptance command after the last covered-artifact change and bind exact hashes.", requiredEvidence: ["original command", "exit status", "current artifact versions"], invalidSubstitutes: ["earlier passing output", "changed easier command", "agent success statement"], failureAction: "repair and rerun the original acceptance condition", confidence: .98, cost: 1, successfulRuns: [], counterexamples: [] },
];
